# Site settings
title: HiDream Team
SEOTitle: "Hi 技术 团队"
email: hidream_tech@163.com
description: "打造nb的团队,nb的产品"
keyword: "前端 后端 ios iOS Android android 测试 运维 产品"
baseurl: "/"
url: "www.hidream.tech"

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
    - tables
  enable_coderay: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    coderay_line_numbers:  nil

gems: 
  - jekyll-paginate
  - jekyll-seo-tag

excerpt : teaser
paginate : 5
paginate_path : "/page:num/"

comments :
  provider : duoshuo
  duoshuo :
    short_name : hidream

baidu_analyze: d9da9bb820e87945d7717a17c257a67d
